### PR TITLE
Fix typing with mypy, add marker file

### PR DESCRIPTION
**Pull request by Rafiot**
Just a few changes to make mypy happy and allow the code using this module to use on the typing ([py.typed](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)).

A few notes: 
* `query_recent` ignores the actual value of `selector` and always passes either `100` or `time`. I made 100 a string because the `data` parameter in `post` seems to expect `Dict[str, str]`, I didn't investigate further, but passing an `int` shouldn't be an issue and I'm unsure why mypy complained.
* Not sure what `from malwarebazaar import commit` is in `malwarebazaar/commands/version.py`? 
* os.path.join with a potential `None` part would cause an exception anyway, so I just raise one.

### CODE REVIEW

**Comment by 3c7** [comment]
Taking a look later, just for now:

`from malwarebazaar import commit` -> `commit` includes the commit hash during build process in https://github.com/3c7/bazaar/blob/main/.github/pyinstaller/bazaar.spec. Don't know if this is the proper way to do it, though. If someone uses the binary, they can check the commit hash with the version command.

**Comment by 3c7** [comment]
And thanks for the PR, of course. :)

**Comment by Rafiot** [comment]
You're welcome, thank you for the module :)

**Comment by 3c7** [comment]
Regarding

> query_recent ignores the actual value of selector and always passes either 100 or time

The API expects either `100` or `time`. Found that also confusing. :D https://bazaar.abuse.ch/api/#latest_additions

**Comment by 3c7** [comment]
Are the `Optional[]` type hints removal are result of the mypy type checker? If so, I'm wondering why there are no changes in other files beside `output.py`...

**Comment by Rafiot** [comment]
The `Optional[Console]` are superfluous in `output.py` because if nothing is passed to the method, a new instance is created. In the other files, it is afaik needed.

**Pull request merged**
